.TH "MOPHERD" "1" "December 2009"
.SH NAME
.B mopherd \- mopher mail filter daemon
.SH SYNOPSIS
mopherd [-Cfh] [-c config_file] [-d debug_level]
.SH DESCRIPTION
.B mopherd
is a modular mail filter (milter) daemon.
.B mopherd
uses two configuration files:
.BR mopherd.conf "(5) which contains the mopherd configuration parameters and"
.BR mail.acl "(5) which controls how mopherd filters incoming emails."
.SH OPTIONS
Executed without any parameters mopherd will detach into background and write
logging and debugging information to syslog (LOG_MAIL facility).
.PP
Options:
.IP "\fB-c \fIconfig_file\fR"
Filesystem path for the mopherd configuration file. If not specified mopherd
will use the default path: \fB$MOPHERD_CONF\fR
.IP "\fB-C\fR"
Run a configuration check only. If mopherd returns an exit code other
than 0, configuration errors were detected. To see debugging output also set
\fB-f\fR to log error messages to stderr.
.IP "\fB-d \fIdebug_level\fR"
Set log verbosity. \fIdebug_level\fR is an integer value ranging from 0
(quiet) to 7 (full debug output).
.IP "\fB-f\fR"
Don't detach into background. Useful for debugging.
.IP "\fB-h\fR"
Show help.
.SH FILES
$MOPHERD_CONF, $MAIL_ACL
.SH SEE ALSO
.nf
.BR mopherd.conf "(5), mopherd configuration file"
.BR mail.acl "(5), mopherd mail access control list"
.fi
.SH AUTHORS
Manuel Badzong <manuel@andev.ch>
